"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
var dotenv_1 = __importDefault(require("dotenv"));
require("reflect-metadata"); // Usa por causa dos decorators
var express_1 = __importDefault(require("express"));
require("express-async-errors");
var routes_1 = __importDefault(require("./routes"));
require("./database");
var AppError_1 = __importDefault(require("./errors/AppError"));
dotenv_1.default.config();
var app = express_1.default();
app.use(express_1.default.json());
app.use(routes_1.default);
app.use(function (erro, request, response, next) {
    // Quer dizer que o erro foi originado pelo AppError, ent√£o √© um erro que j√° conhecemos
    if (erro instanceof AppError_1.default) {
        return response.status(erro.statusCode).json({
            status: 'Erro',
            message: erro.mensagem,
        });
    }
    // A partir daqui √© um erro desconhecido, que ser√° necess√°rio o uso do console para poder identificar
    console.error(erro);
    return response.status(500).json({
        status: 'Erro',
        message: 'Erro interno no serviror',
    });
});
app.listen(process.env.PORT || 3333, function () {
    console.log(' ');
    console.log('Servidor rodando... üöÄ');
    console.log('http://localhost:3333/');
    console.log(' ');
});
